export const Colors = {
  primary: '#4A154B',
  yellow: '#FFCB37',
  white: '#FFF',
  blue: '#36C5F0',
  black: '#2e2e2e',
  green: '#2EB67D',
  secondaryText: '#7B7B7B',
  red: '#E01E5A',
  inactiveIcon: '#C4C4C4',
  ingredientGreen: '#87D5A7',
  ingredientBlue: '#33CEE3',
  ingredientPurple: '#DCA0E5',
  ingredientRed: '#EF8686',
  ingredientYellow: '#FCD55D',
  instructionBack: '#FFEFDB',
  stepNo: '#FFB23D',
  colorLine: 'rgb(221, 221, 221)',

  // Transparent colors
  redTrans: 'rgba(255,88,93, 0.7)',
  greenTrans: 'rgba(135,213,167, 0.7)',
  greyTrans: 'rgba(123,123,123, 0.7)',
};

export const Images = {
  imgWelcome: require('../assets/images/mock-img.png'),
  iconGoogle: require('../assets/images/google.png'),
  iconFacebook: require('../assets/images/facebook.png'),
  iconTwitter: require('../assets/images/twitter.png'),
  iconSettings: require('../assets/images/settings.png'),
  iconMenu: require('../assets/images/menu.png'),
  iconHome: require('../assets/images/icon-home.png'),
  iconSearch: require('../assets/images/icon-search.png'),
  iconAdd: require('../assets/images/icon-add.png'),
  iconFav: require('../assets/images/icon-fav.png'),
  iconSave: require('../assets/images/icon-save.png'),
  iconStar: require('../assets/images/icon-star.png'),
  iconSaveOutline: require('../assets/images/icon-outline-save.png'),
  iconSaveOutlineWide: require('../assets/images/icon-outline-save-wide.png'),
  iconLikeOutline: require('../assets/images/icon-outline-fav.png'),
  iconShare: require('../assets/images/icon-share.png'),
  iconExplore: require('../assets/images/icon-explore.png'),
  iconTimer: require('../assets/images/icon-timer.png'),
  iconServe: require('../assets/images/icon-serve.png'),
  iconBurn: require('../assets/images/icon-burn.png'),
  iconOkay: require('../assets/images/icon-okay.png'),
  iconCross: require('../assets/images/icon-cross.png'),
  iconAvatar: require('../assets/images/avatar.png'),
  iconBack: require('../assets/images/icon-back.png'),
  img1: require('../assets/images/img-1.png'),
  img2: require('../assets/images/img-2.png'),
  img3: require('../assets/images/img-3.png'),
  img4: require('../assets/images/img-4.png'),
  person1: require('../assets/images/person-1.png'),
  person2: require('../assets/images/person-2.png'),
  person3: require('../assets/images/person-3.png'),
  person4: require('../assets/images/person-4.png'),
};

export const Titles = {
  AppName: 'foodigram',
  WelcomeAppDesc: 'Let’s dive in the world of bests \n by best chefs worldwide',
  OtherSignInOption: '\nor via social media',
};
